theme: jekyll-theme-slate
title: Glaucoma screening | Cost-effective simulation 
description: Skeleton repository on building simulation for having a cost-effective strategy for population-level screening for glaucoma
